#+author: J. Dylan White
#+title: Reading Pokemon Data from PokemonDB

* Introduction

[[https://pokemondb.net][PokemonDB]] is a great resource for getting Pokemon data. The data for each Pokemon is in a pretty consistent format, so scraping the data programmatically should be relatively simple.

* Dependencies

In order to scrape data from webpages using R, I will be using the =rvest= package. This required me to install =openssl= and =curl=. Using Fedora, I installed them via

#+begin_src shell

  sudo dnf install openssl-devel
  sudo dnf install libcurl-devel

#+end_src

After this, I was succesfully able to install =rvest= in R using

#+begin_src R

  install.packages("rvest")

#+end_src

* Scraping PokemonDB with R

Now, using =rvest=, let's scrape the data from a page for a specific Pokemon, Gengar.

#+begin_src R :results output :session *R*

  # Use the rvest package for scraping data
  library(rvest)
  library(dplyr)

  # Set the URL to fetch data from
  url <- "https://pokemondb.net/pokedex/gengar"

  # Read the URL
  read_html(url)

#+end_src

#+RESULTS:
: {html_document}
: <html lang="en">
: [1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\n<meta charset="utf-8">\n<title>Gengar Pokédex: stats, moves, evolution &amp; locations | Pokémon Database</title>\n<link rel ...
: [2] <body>\n<a class="sr-only" href="#main">Skip to main content</a>\n<header class="main-header"><div class="grid-container">\n<a href="/" class="header-logo">\n<picture><source type="image/avif" media="( ...

We have the content of the HTML document for the page, but let's extract more meaningful data from the page now, such as the Pokemon's type.

** Pokemon Type

#+begin_src R :results output :session *R*

  # Read the body from the page
  body <- url %>% read_html() %>% html_nodes("body")

  # Get the table with the "type" information
  ## typeTable <- 
  html_table(html_nodes(body,"table.vitals-table")[1])
  #

#+end_src

#+RESULTS:
#+begin_example
[[1]]
[90m# A tibble: 7 × 2[39m
  X1         X2                                                                                                                                                                                                 
  [3m[90m<chr>[39m[23m      [3m[90m<chr>[39m[23m                                                                                                                                                                                              
[90m1[39m National № 0094                                                                                                                                                                                               
[90m2[39m Type       Ghost Poison                                                                                                                                                                                       
[90m3[39m Species    Shadow Pokémon                                                                                                                                                                                     
[90m4[39m Height     1.5 m (4′11″)                                                                                                                                                                                      
[90m5[39m Weight     40.5 kg (89.3 lbs)                                                                                                                                                                                 
[90m6[39m Abilities  1. Cursed Body                                                                                                                                                                                     
[90m7[39m Local №    0094 (Red/Blue/Yellow)0060 (Gold/Silver/Crystal)0094 (FireRed/LeafGreen)0071 (Diamond/Pearl)0071 (Platinum)0060 (HeartGold/SoulSilver)0032 (X/Y — Mountain Kalos)0063 (Sun/Moon — Alola dex)0075 (…
#+end_example

